# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(612, 476)
        self.user_text_browser = QtWidgets.QTextBrowser(Form)
        self.user_text_browser.setGeometry(QtCore.QRect(130, 20, 361, 121))
        self.user_text_browser.setStyleSheet("border: 1px solid #e0e0e0; border - radius: 5px; padding: 10px;")
        self.user_text_browser.setObjectName("user_text_browser")
        self.ai_text_browser = QtWidgets.QTextBrowser(Form)
        self.ai_text_browser.setGeometry(QtCore.QRect(130, 150, 361, 121))
        self.ai_text_browser.setStyleSheet("border: 1px solid #e0e0e0; border - radius: 5px; padding: 10px;")
        self.ai_text_browser.setObjectName("ai_text_browser")
        self.input_edit = QtWidgets.QLineEdit(Form)
        self.input_edit.setGeometry(QtCore.QRect(160, 300, 241, 41))
        self.input_edit.setObjectName("input_edit")
        self.send_btn = QtWidgets.QPushButton(Form)
        self.send_btn.setGeometry(QtCore.QRect(420, 300, 51, 41))
        self.send_btn.setStyleSheet("background - color: #4CAF50; color: white; border - radius: 5px;")
        self.send_btn.setObjectName("send_btn")
        self.power_btn = QtWidgets.QPushButton(Form)
        self.power_btn.setEnabled(True)
        self.power_btn.setGeometry(QtCore.QRect(40, 380, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_btn.sizePolicy().hasHeightForWidth())
        self.power_btn.setSizePolicy(sizePolicy)
        self.power_btn.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.power_btn.setObjectName("power_btn")
        self.act_btn = QtWidgets.QPushButton(Form)
        self.act_btn.setGeometry(QtCore.QRect(430, 390, 111, 51))
        self.act_btn.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: black; /* 文字颜色 */\n"
"    border - radius: 5px; /* 小圆角 */\n"
"    padding: 8px 16px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.act_btn.setObjectName("act_btn")
        self.set_up_btn = QtWidgets.QPushButton(Form)
        self.set_up_btn.setGeometry(QtCore.QRect(130, 380, 60, 60))
        self.set_up_btn.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.set_up_btn.setObjectName("set_up_btn")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 380, 60, 60))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(310, 380, 60, 60))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(30, 30, 61, 321))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton_1 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(520, 40, 61, 321))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0; /* 背景色 */\n"
"    color: white; /* 文字颜色 */\n"
"    border - radius: 30px; /* 圆角半径，实现圆形效果 */\n"
"    padding: 10px; /* 内边距 */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF8A80; /* 悬停时背景色变化 */\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_edit.setPlaceholderText(_translate("Form", "\"输入消息\""))
        self.send_btn.setText(_translate("Form", "发送"))
        self.power_btn.setText(_translate("Form", "电源"))
        self.act_btn.setText(_translate("Form", "启动"))
        self.set_up_btn.setText(_translate("Form", "设置"))
        self.pushButton_9.setText(_translate("Form", "功能9"))
        self.pushButton_10.setText(_translate("Form", "功能10"))
        self.pushButton_1.setText(_translate("Form", "功能1"))
        self.pushButton_2.setText(_translate("Form", "功能2"))
        self.pushButton_3.setText(_translate("Form", "功能3"))
        self.pushButton_4.setText(_translate("Form", "功能4"))
        self.pushButton_5.setText(_translate("Form", "功能5"))
        self.pushButton_6.setText(_translate("Form", "功能6"))
        self.pushButton_7.setText(_translate("Form", "功能7"))
        self.pushButton_8.setText(_translate("Form", "功能8"))
